-- Subscription cost account tables
create table if not exists sa_subscription_cost_files (
  id uuid primary key default gen_random_uuid(),
  uploaded_at timestamptz default now(),
  uploaded_by uuid references auth.users(id),
  original_filename text not null,
  storage_path text,
  style text not null,
  item_count int default 0,
  matched_count int default 0
);

create table if not exists sa_subscription_cost_items (
  id uuid primary key default gen_random_uuid(),
  file_id uuid references sa_subscription_cost_files(id) on delete cascade,
  style text not null,
  retail_customer text,
  legal_name text,
  org_name text,
  customer_name text,
  location text,
  ordered_by text,
  matched_customer_id uuid references sa_customers(id),
  matched_sold_item_id uuid,
  amount numeric(12,2),
  currency text default 'USD',
  invoice_number text,
  order_number text,
  description text,
  serial_number text,
  item_number text,
  contract_start date,
  contract_end date,
  due_date date,
  raw_text text,
  created_at timestamptz default now()
);

create index if not exists sa_subscription_cost_items_file_id_idx
  on sa_subscription_cost_items(file_id);

create index if not exists sa_subscription_cost_items_matched_customer_idx
  on sa_subscription_cost_items(matched_customer_id);

-- Subscription sold-to tables
create table if not exists sa_subscription_sold_files (
  id uuid primary key default gen_random_uuid(),
  uploaded_at timestamptz default now(),
  uploaded_by uuid references auth.users(id),
  original_filename text not null,
  storage_path text,
  item_count int default 0,
  matched_count int default 0,
  upload_number bigint generated by default as identity,
  matched_cost_file_id uuid references sa_subscription_cost_files(id),
  matched_at timestamptz,
  locked_at timestamptz,
  locked_by uuid references auth.users(id)
);

create table if not exists sa_subscription_sold_items (
  id uuid primary key default gen_random_uuid(),
  file_id uuid references sa_subscription_sold_files(id) on delete cascade,
  invoice_number text,
  invoice_date date,
  customer_name text,
  retail_price numeric(12,2),
  description text,
  serial_number text,
  sold_by text,
  location text,
  item_number text,
  matched_cost_item_id uuid,
  matched_customer_id uuid references sa_customers(id),
  raw_text text,
  created_at timestamptz default now()
);

create index if not exists sa_subscription_sold_items_file_id_idx
  on sa_subscription_sold_items(file_id);

create index if not exists sa_subscription_sold_items_matched_customer_idx
  on sa_subscription_sold_items(matched_customer_id);

-- Location code mappings (e.g., ISACTIVE1 -> Bucklin)
create table if not exists sa_location_codes (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  location_name text not null,
  created_at timestamptz default now()
);

-- Account number mappings per location (used in Change Location print PDFs)
create table if not exists sa_location_account_numbers (
  id uuid primary key default gen_random_uuid(),
  location_name text unique not null,
  account_number text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists sa_location_account_numbers_location_idx
  on sa_location_account_numbers(location_name);

-- Sold-to account number mappings per location
create table if not exists sa_location_sold_account_numbers (
  id uuid primary key default gen_random_uuid(),
  location_name text unique not null,
  account_number text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists sa_location_sold_account_numbers_location_idx
  on sa_location_sold_account_numbers(location_name);

-- App settings (feature toggles, flags)
create table if not exists sa_app_settings (
  key text primary key,
  value text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create or replace function sa_set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists sa_location_account_numbers_set_updated_at
  on sa_location_account_numbers;

create trigger sa_location_account_numbers_set_updated_at
before update on sa_location_account_numbers
for each row
execute function sa_set_updated_at();

drop trigger if exists sa_app_settings_set_updated_at
  on sa_app_settings;

create trigger sa_app_settings_set_updated_at
before update on sa_app_settings
for each row
execute function sa_set_updated_at();

drop trigger if exists sa_location_sold_account_numbers_set_updated_at
  on sa_location_sold_account_numbers;

create trigger sa_location_sold_account_numbers_set_updated_at
before update on sa_location_sold_account_numbers
for each row
execute function sa_set_updated_at();

-- Development notes
create table if not exists sa_development_notes (
  id uuid primary key default gen_random_uuid(),
  note text not null,
  status text not null default 'not_started',
  priority text not null default 'medium',
  created_by uuid references auth.users(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Admin action audit logs (destructive admin tools)
create table if not exists sa_admin_action_logs (
  id uuid primary key default gen_random_uuid(),
  action text not null,
  actor_id uuid references auth.users(id),
  actor_email text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists sa_admin_action_logs_created_at_idx
  on sa_admin_action_logs(created_at desc);

-- Location change requests for cost items
create table if not exists sa_location_change_requests (
  id uuid primary key default gen_random_uuid(),
  cost_item_id uuid references sa_subscription_cost_items(id) on delete cascade,
  sold_item_id uuid references sa_subscription_sold_items(id) on delete cascade,
  from_location text not null,
  to_location text not null,
  customer_name text not null,
  amount numeric(12,2),
  status text default 'pending',
  denial_reason text,
  printed_at timestamptz,
  printed_by uuid references auth.users(id),
  created_at timestamptz default now(),
  created_by uuid references auth.users(id),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id)
);

create index if not exists sa_location_change_requests_cost_item_idx
  on sa_location_change_requests(cost_item_id);

create index if not exists sa_location_change_requests_sold_item_idx
  on sa_location_change_requests(sold_item_id);

-- Saved print files for reprints
create table if not exists sa_location_change_print_files (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  request_count int not null default 0,
  request_ids uuid[] not null default '{}',
  html_content text not null,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create index if not exists sa_location_change_print_files_created_at_idx
  on sa_location_change_print_files(created_at);

-- One-time migration for existing environments.
alter table if exists sa_development_notes
  add column if not exists priority text not null default 'medium';

-- Add matched item id fields for cost-to-sold reconciliation
alter table if exists sa_subscription_cost_items
  add column if not exists matched_sold_item_id uuid;

alter table if exists sa_subscription_sold_items
  add column if not exists matched_cost_item_id uuid;

-- UI wording standardization:
-- Reconclied = existing "matched" fields are populated
-- Not Reconclied = existing "matched" fields are null
comment on column sa_subscription_cost_files.matched_count is
  'Count of Reconclied cost items for this upload.';

comment on column sa_subscription_sold_files.matched_count is
  'Count of Reconclied sold items for this upload.';

comment on column sa_subscription_cost_items.matched_customer_id is
  'Set when the cost item is Reconclied to a customer profile.';

comment on column sa_subscription_cost_items.matched_sold_item_id is
  'Set when the cost item is Reconclied to a sold item.';

comment on column sa_subscription_sold_items.matched_customer_id is
  'Set when the sold item is Reconclied to a customer profile.';

comment on column sa_subscription_sold_items.matched_cost_item_id is
  'Set when the sold item is Reconclied to a cost item.';

-- Ensure item_number columns are text for prefixed IDs (e.g., C-2026-101-1 / R-2026-203-4)
alter table if exists sa_subscription_cost_items
  alter column item_number type text using item_number::text;

alter table if exists sa_subscription_sold_items
  alter column item_number type text using item_number::text;

-- Ensure cost files has upload_number identity column in older environments.
alter table if exists sa_subscription_cost_files
  add column if not exists upload_number bigint generated by default as identity;

-- Reset activation upload numbers from admin tools.
create or replace function sa_reset_activation_upload_number(
  p_kind text,
  p_next_number bigint
)
returns void as $$
begin
  if p_next_number < 1 then
    raise exception 'p_next_number must be >= 1';
  end if;

  if p_kind = 'cost' then
    execute format(
      'alter table public.sa_subscription_cost_files alter column upload_number restart with %s',
      p_next_number
    );
  elsif p_kind = 'sold' then
    execute format(
      'alter table public.sa_subscription_sold_files alter column upload_number restart with %s',
      p_next_number
    );
  else
    raise exception 'Unsupported kind: %', p_kind;
  end if;
end;
$$ language plpgsql security definer;

-- Ensure location change request columns exist in older environments.
alter table if exists sa_location_change_requests
  add column if not exists status text default 'pending';

alter table if exists sa_location_change_requests
  add column if not exists sold_item_id uuid references sa_subscription_sold_items(id);

alter table if exists sa_location_change_requests
  alter column cost_item_id drop not null;

alter table if exists sa_location_change_requests
  add column if not exists denial_reason text;

alter table if exists sa_location_change_requests
  add column if not exists printed_at timestamptz;

alter table if exists sa_location_change_requests
  add column if not exists printed_by uuid references auth.users(id);

alter table if exists sa_location_change_requests
  add column if not exists reviewed_at timestamptz;

alter table if exists sa_location_change_requests
  add column if not exists reviewed_by uuid references auth.users(id);

create index if not exists sa_location_change_requests_status_idx
  on sa_location_change_requests(status);

create index if not exists sa_location_change_requests_printed_at_idx
  on sa_location_change_requests(printed_at);

-- Manual cleanup helper for pre-launch data resets.
-- Usage:
--   select sa_clear_test_data('CLEAR_IS_DEPT_TEST_DATA');
--   select sa_clear_test_data('CLEAR_IS_DEPT_TEST_DATA', false); -- also clears location codes/account mappings
create or replace function sa_clear_test_data(
  confirm_text text,
  keep_reference_data boolean default true
)
returns void as $$
declare
  table_name text;
  truncate_list text := '';
  core_tables text[] := array[
    'sa_admin_action_logs',
    'sa_location_change_print_files',
    'sa_location_change_requests',
    'sa_subscription_cost_items',
    'sa_subscription_sold_items',
    'sa_subscription_cost_files',
    'sa_subscription_sold_files',
    'sa_development_notes',
    'sa_tasks',
    'sa_equipment',
    'sa_customers'
  ];
  reference_tables text[] := array[
    'sa_location_codes',
    'sa_location_account_numbers',
    'sa_location_sold_account_numbers',
    'sa_app_settings',
    'sa_xid_consultants'
  ];
begin
  if confirm_text <> 'CLEAR_IS_DEPT_TEST_DATA' then
    raise exception 'Confirmation text mismatch. Expected CLEAR_IS_DEPT_TEST_DATA';
  end if;

  foreach table_name in array core_tables loop
    if to_regclass(format('public.%I', table_name)) is not null then
      truncate_list := concat_ws(', ', truncate_list, format('public.%I', table_name));
    end if;
  end loop;

  if not keep_reference_data then
    foreach table_name in array reference_tables loop
      if to_regclass(format('public.%I', table_name)) is not null then
        truncate_list := concat_ws(', ', truncate_list, format('public.%I', table_name));
      end if;
    end loop;
  end if;

  if truncate_list <> '' then
    execute 'truncate table ' || truncate_list || ' restart identity cascade';
  end if;
end;
$$ language plpgsql;


-- XID to IS Consultant name mappings
create table if not exists sa_xid_consultants (
  id uuid primary key default gen_random_uuid(),
  xid text unique not null,
  name text not null,
  created_at timestamptz default now()
);

create index if not exists sa_xid_consultants_xid_idx
  on sa_xid_consultants(xid);

-- Business system check numbers
create table if not exists sa_business_check_numbers (
  id uuid primary key default gen_random_uuid(),
  check_date date not null,
  location_name text not null,
  cost_total numeric(12,2) not null default 0,
  sold_total numeric(12,2) not null default 0,
  notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create trigger sa_business_check_numbers_updated_at
  before update on sa_business_check_numbers
  for each row execute function sa_set_updated_at();

-- =============================================================
-- Row Level Security
-- All sa_ tables are accessed exclusively through API routes
-- that use the service role key (which bypasses RLS).
-- Enabling RLS with no anon policies prevents direct database
-- access via the public anon key.
-- =============================================================
alter table sa_subscription_cost_files enable row level security;
alter table sa_subscription_cost_items enable row level security;
alter table sa_subscription_sold_files enable row level security;
alter table sa_subscription_sold_items enable row level security;
alter table sa_location_codes enable row level security;
alter table sa_location_account_numbers enable row level security;
alter table sa_location_sold_account_numbers enable row level security;
alter table sa_app_settings enable row level security;
alter table sa_development_notes enable row level security;
alter table sa_admin_action_logs enable row level security;
alter table sa_location_change_requests enable row level security;
alter table sa_location_change_print_files enable row level security;
alter table sa_xid_consultants enable row level security;
alter table sa_business_check_numbers enable row level security;
